---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore caddy module as this is upgraded manually as required
      - dependency-name: "github.com/caddyserver/caddy/v2"
